---
# disable swap
- name: Disabling Swap on all nodes
  shell: swapoff -a

# disable auto mount swap
- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: Disable firewall
  systemd:
    name: firewalld
    state: stopped

# Letting iptables see bridged traffic
- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Set system ip6tables config
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes

- name: Set system swap config
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: yes

- name: Set system iptables config
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Remove legacy docker repo file
  file:
    path: "{{ yum_repo_dir }}/docker.repo"
    state: absent
  when:
    - ansible_distribution in ["CentOS","RedHat","OracleLinux"]

- name: Ensure old versions of Docker are not installed. | Debian
  apt:
    name: '{{ docker_remove_packages_apt }}'
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))

- name: Ensure old versions of Docker are not installed. | RedHat
  yum:
    name: '{{ docker_remove_packages_yum }}'
    state: absent
  when:
    - ansible_os_family == 'RedHat'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))