- name: Uninstall old versions
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent

- name: Install list of packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch="{{ apt__architecture }}"] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker CE
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes

- name: Ensure docker service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: sudo, docker
    append: yes
  become: yes

- name: Install prerequisites for docker-compose
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv']

- name: Install docker-compose
  pip:
    name: docker-compose